-- Seed 87 doctors from the new static HNH site
-- Match the actual providers table schema:
-- provider_code, first_name_ar, first_name_en, last_name_ar, last_name_en, 
-- specialty, department, clinic_location, phone, email, is_active
INSERT OR IGNORE INTO providers 
(provider_code, first_name_ar, first_name_en, last_name_ar, last_name_en, specialty, department, clinic_location, is_active)
VALUES
('SSD001','معاوية','Muawiya','دبورة','Daboura','Plastic Surgery','جراحة التجميل','Riyadh',1),
('SSD002','نهله','Nahla Taleb','طالب ديب','Deeb','OB/GYN','النساء والولادة','Riyadh',1),
('SSD003','وسام','Wisam','فاروق','Farouk','OB/GYN','النساء والولادة','Riyadh',1),
('SSD004','أميرة','Amira','البيلي','Al-Bili','Dermatology','الجلدية','Riyadh',1),
('SSD005','شامية','Shamia Mohamed','محمد فتحي','Fathy','OB/GYN','النساء والولادة','Riyadh',1),
('SSD006','أحمد','Ahmed Abu','أبو هديمة','Hudaima','Internal Medicine','الباطنية','Madinah',1),
('SSD007','أحمد','Ahmed','أمين صالح حسين','Amin','Orthopedics','العظام','Riyadh',1),
('SSD008','أحمد','Ahmed Al-Saeed','السعيد عبد الهادي','Abd al-Hadi','Cardiology','القلب','Jazan',1),
('SSD009','أحمد','Ahmed Al-Awamri','العوامري','Al-Awamri','ENT','الأنف والأذن','Khamis Mushayt',1),
('SSD010','أحمد','Ahmed Hosni','حسني ندا','Nada','Urology','المسالك البولية','Riyadh',1),
('SSD011','أحمد','Ahmed','حمود أحمد فهمي','Hamoud','Neurology','الأعصاب','Madinah',1),
('SSD012','أحمد','Ahmed','لطفي المشد','Lotfy','General Surgery','الجراحة العامة','Jazan',1),
('SSD013','أحمد','Ahmed','مسعد بيومي','Massad','Internal Medicine','الباطنية','Unayzah',1),
('SSD014','أحمد','Ahmed','نبيل خلاف','Nabil','General Medicine','الطب العام','Khamis Mushayt',1),
('SSD015','أسامه','Osama Al-Mansour','أحمد المنصور','Ahmed','Urology','المسالك البولية','Riyadh',1),
('SSD016','أسماء','Asmaa','فوزي أحمد','Fawzi','OB/GYN','النساء والولادة','Madinah',1),
('SSD017','أشرف','Ashraf','عبدالله مرسي','Abdallah','Plastic Surgery','التجميل','Riyadh',1),
('SSD018','إبراهيم','Ibrahim','أحمد إبراهيم','Ahmed','Orthopedics','العظام','Jazan',1),
('SSD019','إسلام','Islam','فتحي محمد عوض','Fathy','Dermatology','الجلدية','Khamis Mushayt',1),
('SSD020','إبراهيم','Ibrahim Al-Qarmout','محمد القرموط','Mohamed','Cardiology','القلب','Riyadh',1),
('SSD021','أحمد','Ahmed','أسامة عبد المجيد','Osama','Pediatrics','الأطفال','Madinah',1),
('SSD022','أحمد','Ahmed Al-Heezi','الهيزي','Heezi','ENT','الأنف والأذن','Unayzah',1),
('SSD023','أحمد','Ahmed','حسانيين','Hassanein','Internal Medicine','الباطنية','Jazan',1),
('SSD024','أحمد','Ahmed','سلامة ناصر','Salama','Orthopedics','العظام','Riyadh',1),
('SSD025','أحمد','Ahmed','صلاح الدين مصطفى','Salah','Neurology','الأعصاب','Khamis Mushayt',1),
('SSD026','أحمد','Ahmed','محمد مصطفى','Mohamed','General Surgery','الجراحة العامة','Madinah',1),
('SSD027','إسلام','Islam','أحمد محمد','Ahmed','OB/GYN','النساء والولادة','Unayzah',1),
('SSD028','إسلام','Islam','شلبي','Shalaby','General Medicine','الطب العام','Jazan',1),
('SSD029','إسلام','Islam Mohamed','محمد عبد الغفار','Abd al-Ghaffar','Internal Medicine','الباطنية','Riyadh',1),
('SSD030','إسماء','Ismaa','محمد علي','Mohamed','Pediatrics','الأطفال','Khamis Mushayt',1),
('SSD031','الآء','Alaa','ماجد ابو جامع','Majed','Dermatology','الجلدية','Madinah',1),
('SSD032','الحسين','Al-Hussein','محمد خواجي','Mohamed','Cardiology','القلب','Riyadh',1),
('SSD033','السعودي','Al-Saudi','الشاعر','Al-Shaer','Orthopedics','العظام','Unayzah',1),
('SSD034','أميرة','Amira','عادل الحفني','Adel','OB/GYN','النساء والولادة','Jazan',1),
('SSD035','بهاء','Bahaa','الدين جابر','Gaber','Neurology','الأعصاب','Riyadh',1),
('SSD036','جلال','Jalal','حمود ابو حليمة','Hamoud','Internal Medicine','الباطنية','Khamis Mushayt',1),
('SSD037','جيهان','Gihan','حمدي','Hamdy','OB/GYN','النساء والولادة','Madinah',1),
('SSD038','حسام','Hossam Abu','أبو موسى','Moussa','Plastic Surgery','التجميل','Riyadh',1),
('SSD039','حسام','Hossam','محمود مختار','Mahmoud','General Surgery','الجراحة العامة','Jazan',1),
('SSD040','حسين','Hussein','إبراهيم قصادي','Ibrahim','ENT','الأنف والأذن','Unayzah',1),
('SSD041','خالد','Khaled Al-Rajhi','الراجحي','Al-Rajhi','Orthopedics','العظام','Riyadh',1),
('SSD042','خالد','Khaled','مصباح صلاح','Misbah','Cardiology','القلب','Khamis Mushayt',1),
('SSD043','ديمه','Dima','عبدالله','Abdallah','General Medicine','الطب العام','Madinah',1),
('SSD044','رانيا','Rania','عزت عامر','Ezzat','OB/GYN','النساء والولادة','Riyadh',1),
('SSD045','زينب','Zeinab','أحمد التاجاني','Ahmed','Pediatrics','الأطفال','Jazan',1),
('SSD046','سارة','Sarah','مدحت إبراهيم','Medhat','Dermatology','الجلدية','Unayzah',1),
('SSD047','سارة','Sarah','هاشم محمد','Hashem','Internal Medicine','الباطنية','Riyadh',1),
('SSD048','سامح','Sameh Al-Garf','محمد الجرف','Mohamed','Neurology','الأعصاب','Khamis Mushayt',1),
('SSD049','سحر','Sahar','حسيني','Hosseini','OB/GYN','النساء والولادة','Madinah',1),
('SSD050','سلوى','Salwa Abu Al-Fotouh','ابو الفتاح','Al-Fotouh','Pediatrics','الأطفال','Riyadh',1),
('SSD051','سميرة','Samira','عبدالرؤوف','Abdulraouf','General Medicine','الطب العام','Jazan',1),
('SSD052','شروق','Shorouk','عادل محمد','Adel','Dermatology','الجلدية','Unayzah',1),
('SSD053','صفاء','Safaa','إبراهيم أحمد','Ibrahim','Internal Medicine','الباطنية','Khamis Mushayt',1),
('SSD054','طارق','Tarek','إبراهيم محمد','Ibrahim','General Surgery','الجراحة العامة','Riyadh',1),
('SSD055','طاهر','Taher','بن يحيى صميلي','Yahya','ENT','الأنف والأذن','Madinah',1),
('SSD056','ظافر','Dhaffer Al-Shahrani','محمد الشهري','Mohamed','Orthopedics','العظام','Khamis Mushayt',1),
('SSD057','عائشة','Aisha Al-Rifai','الرفاعي','Al-Rifai','OB/GYN','النساء والولادة','Riyadh',1),
('SSD058','عادل','Adel','لملوم','Lamloum','Cardiology','القلب','Jazan',1),
('SSD059','عبدالله','Abdallah Al-Hilali','الهلالي','Al-Hilali','Urology','المسالك البولية','Unayzah',1),
('SSD060','عبدالله','Abdallah','بن عبدالعزيز','bin Abdulaziz','Neurology','الأعصاب','Riyadh',1),
('SSD061','عبدالله','Abdallah','يوسف المرشد','Youssef','Internal Medicine','الباطنية','Madinah',1),
('SSD062','عبدالنبي','Abdulnabi','الدخشان','Al-Dakhshan','General Surgery','الجراحة العامة','Khamis Mushayt',1),
('SSD063','عزه','Azza','جمال محمد','Gamal','OB/GYN','النساء والولادة','Riyadh',1),
('SSD064','عماد','Emad','الدين محمد','Eddin','Pediatrics','الأطفال','Jazan',1),
('SSD065','عماد','Emad','حمدي طايل','Hamdy','Orthopedics','العظام','Unayzah',1),
('SSD066','عمرو','Amr','جلال بسيوني','Jalal','Cardiology','القلب','Riyadh',1),
('SSD067','عمرو','Amr','مصطفى الدرديري','Mostafa','Internal Medicine','الباطنية','Khamis Mushayt',1),
('SSD068','فادية','Fadia','نبهان تركي','Nabhan','Dermatology','الجلدية','Madinah',1),
('SSD069','فادية','Fadia','عبدالله خيري','Abdallah','OB/GYN','النساء والولادة','Riyadh',1),
('SSD070','كريم','Karim','نصر علي','Nasr','Neurology','الأعصاب','Jazan',1),
('SSD071','محمد','Mohamed Al-Ahzami','أحمد الأحزمي','Ahmed','Orthopedics','العظام','Unayzah',1),
('SSD072','محمد','Mohamed','إسماعيل غريب','Ismail','General Surgery','الجراحة العامة','Riyadh',1),
('SSD073','محمد','Mohamed','إبراهيم المعاطي','Ibrahim','Internal Medicine','الباطنية','Khamis Mushayt',1),
('SSD074','محمد','Mohamed Al-Shafi','الشافعي','Al-Shafi','ENT','الأنف والأذن','Madinah',1),
('SSD075','محمد','Mohamed Al-Shabrawy','الشبراوي','Al-Shabrawy','Cardiology','القلب','Riyadh',1),
('SSD076','محمد','Mohamed Al-Dale','الضالع','Al-Dale','Urology','المسالك البولية','Jazan',1),
('SSD077','محمد','Mohamed Al-Awdi','العوضي','Al-Awdi','Pediatrics','الأطفال','Unayzah',1),
('SSD078','محمد','Mohamed','حامد أبوالفضل','Hamid','Orthopedics','العظام','Riyadh',1),
('SSD079','محمد','Mohamed','سعيد سلامة','Saeed','Internal Medicine','الباطنية','Khamis Mushayt',1),
('SSD080','محمد','Mohamed','سليمان حجازي','Soliman','Neurology','الأعصاب','Madinah',1),
('SSD081','محمد','Mohamed','صابر محمد','Saber','General Surgery','الجراحة العامة','Riyadh',1),
('SSD082','محمد','Mohamed','صالح حميدة','Saleh','Dermatology','الجلدية','Jazan',1),
('SSD083','محمد','Mohamed','عبد اللطيف','Abd al-Latif','Cardiology','القلب','Unayzah',1),
('SSD084','محمد','Mohamed','عبد الرؤوف السيسي','Abd al-Raouf','OB/GYN','النساء والولادة','Riyadh',1),
('SSD085','محمد','Mohamed','مدخلي','Madkhali','Emergency Medicine','الطوارئ','Khamis Mushayt',1),
('SSD086','محمد','Mohamed','محمد مجدي','Magdy','General Medicine','الطب العام','Madinah',1),
('SSD087','محمد','Mohamed','مؤنس محمد','Mounes','Neurology','الأعصاب','Riyadh',1);
