export const branches = [
  {
    id: 'R001',
    name_ar: 'مستشفى الحياة الوطني - الرياض',
    name_en: 'Hayat National Hospital - Riyadh',
    city_ar: 'الرياض',
    city_en: 'Riyadh',
    address_ar: 'حي الربوة، طريق الفرع الدائري الشرقي',
    address_en: 'Eastern Ring Branch Road, Al-Rabwa District, Riyadh',
    phone: '+966920000094',
    emergency: '+966920000094',
    email: 'info@hayathospitals.com',
    subdomain: 'riyadh.hayathospitals.com',
    offers_ar: 'خصومات للمرضى المنومين لفترات طويلة، برنامج زراعة خاص',
    offers_en: 'Long-stay patient discounts, special transplant program',
    departments: ['emergency','internal','surgery','cardiology','neurology','orthopedics','pediatrics','obgyn','ophthalmology','dentistry','psychiatry','radiology','laboratory','pharmacy','urology','ent','dermatology','gastroenterology','nephrology','endocrinology','rheumatology','oncology','neurosurgery','vascular_surgery','plastic_surgery','pain_clinic'],
    beds: 300,
    established: 2005,
    rating: 4.5,
    lat: 24.7267, lng: 46.6783,
  },
  {
    id: 'J001',
    name_ar: 'مستشفى الحياة الوطني - جازان',
    name_en: 'Hayat National Hospital - Jazan',
    city_ar: 'جازان',
    city_en: 'Jazan',
    address_ar: 'كورنيش جازان، حي الشاطئ',
    address_en: 'Jazan Corniche, Al Shati District',
    phone: '+966920000094',
    emergency: '+966920000094',
    email: 'info@hayathospitals.com',
    subdomain: 'jazan.hayathospitals.com',
    offers_ar: 'خصومات على الجراحات، مخيم طبي لجراحات العيون',
    offers_en: 'Surgery discounts, medical camp for eye surgery patients',
    departments: ['emergency','internal','surgery','pediatrics','obgyn','ophthalmology','ent','dermatology','gastroenterology','cardiology','neurology','laboratory','pharmacy'],
    beds: 150,
    established: 2012,
    rating: 4.3,
    lat: 16.8892, lng: 42.5611,
  },
  {
    id: 'K001',
    name_ar: 'مستشفى الحياة الوطني - خميس مشيط',
    name_en: 'Hayat National Hospital - Khamis Mushayt',
    city_ar: 'خميس مشيط',
    city_en: 'Khamis Mushayt',
    address_ar: 'طريق الأمير سلطان، أم سرار',
    address_en: 'Prince Sultan Road, Umm Sarar',
    phone: '+966538081888',
    phone2: '+966920000094',
    emergency: '+966920000094',
    email: 'info@hayathospitals.com',
    subdomain: 'khamis.hayathospitals.com',
    offers_ar: 'عروض العيون، خصومات الإقامة الطويلة',
    offers_en: 'Ophthalmology promotion, long-stay discounts',
    departments: ['emergency','internal','surgery','pediatrics','obgyn','orthopedics','ophthalmology','ent','dermatology','cardiology','neurology','urology','psychiatry','radiology','laboratory','pharmacy','gastroenterology','nephrology','endocrinology','pulmonology','neurosurgery','rehabilitation'],
    beds: 180,
    established: 2014,
    rating: 4.2,
    lat: 18.3063, lng: 42.7288,
  },
  {
    id: 'M001',
    name_ar: 'مستشفى الحياة الوطني - المدينة المنورة',
    name_en: 'Hayat National Hospital - Madinah',
    city_ar: 'المدينة المنورة',
    city_en: 'Madinah',
    address_ar: 'طريق فرع الهجرة، المدينة المنورة 42316',
    address_en: 'Al-Hijra Branch Road, Madinah 42316',
    phone: '+966920000094',
    emergency: '+966920000094',
    email: 'info@hayathospitals.com',
    offers_ar: 'خدمات طبية باستشاريين متخصصين، خصومات 50+ سنة، فحوصات مجانية',
    offers_en: 'Consultant-led medical services, 50+ senior discounts, free medical tests',
    departments: ['emergency','internal','surgery','cardiology','pediatrics','obgyn','ophthalmology','ent','dermatology','neurology','nephrology','endocrinology','pulmonology','laboratory','pharmacy','rehabilitation'],
    beds: 200,
    established: 2010,
    rating: 4.4,
    lat: 24.4672, lng: 39.6119,
  },
  {
    id: 'U001',
    name_ar: 'مستشفى الحياة الوطني - عنيزة',
    name_en: 'Hayat National Hospital - Unayzah',
    city_ar: 'عنيزة',
    city_en: 'Unayzah',
    address_ar: 'القصيم - عنيزة، طريق المدينة',
    address_en: 'Al-Qassim - Unayzah, Medina Road',
    phone: '+966920000094',
    emergency: '+966920000094',
    email: 'info@hayathospitals.com',
    subdomain: 'unaizah.hayathospitals.com',
    offers_ar: 'عروض مستمرة وعروض الرفاهية',
    offers_en: 'Ongoing promotions and wellness offers',
    departments: ['emergency','internal','surgery','pediatrics','obgyn','ophthalmology','ent','urology','psychiatry','radiology','laboratory','pharmacy','gastroenterology','cardiology','neurology'],
    beds: 120,
    established: 2015,
    rating: 4.1,
    lat: 26.0867, lng: 43.9920,
  },
];

export function getBranches() {
  return branches;
}

export function getBranch(id) {
  return branches.find(b => b.id === id) || null;
}
