-- Additional providers from hayathospitals.com roster
-- Riyadh (R001) - 30 doctors
INSERT OR IGNORE INTO providers (provider_code, first_name_ar, last_name_ar, specialty, department, clinic_location, is_active) VALUES
('RHD001', 'خالد يحيى', 'الشهراني', 'جراحة عظام', 'Orthopedics', 'Riyadh', 1),
('RHD002', 'خالد أحمد', 'الزهراني', 'جراحة عظام', 'Orthopedics', 'Riyadh', 1),
('RHD003', 'محمد', 'الشاكر', 'طب الأسرة', 'Family Medicine', 'Riyadh', 1),
('RHD004', 'أشرف إسماعيل', 'البلتاجي', 'باطنية / كلى', 'Nephrology', 'Riyadh', 1),
('RHD005', 'مصطفى أحمد', 'الأنصاري', 'أطفال / حديثي ولادة', 'Neonatology', 'Riyadh', 1),
('RHD006', 'عثمان', 'سليمان', 'أطفال', 'Pediatrics', 'Riyadh', 1),
('RHD007', 'جميلة سعد', 'القحطاني', 'أطفال', 'Pediatrics', 'Riyadh', 1),
('RHD008', 'عاطف السيد', 'حراز', 'أنف وأذن وحنجرة', 'ENT', 'Riyadh', 1),
('RHD009', 'محمد سيد', 'غريب', 'أنف وأذن وحنجرة', 'ENT', 'Riyadh', 1),
('RHD010', 'شريف صلاح الدين', 'أبو العلا', 'تجميل وجراحة وجه', 'Plastic Surgery', 'Riyadh', 1),
('RHD011', 'حاتم عبداللطيف', 'الضويان', 'جراحة أوعية دموية', 'Vascular Surgery', 'Riyadh', 1),
('RHD012', 'شادي', 'خالد', 'جراحة أوعية دموية', 'Vascular Surgery', 'Riyadh', 1),
('RHD013', 'عمار عبدالله', 'بايونس', 'جراحة سمنة ومنظار', 'Bariatric Surgery', 'Riyadh', 1),
('RHD014', 'وليد مصطفى', 'العقاد', 'جراحة أورام الثدي', 'Oncology', 'Riyadh', 1),
('RHD015', 'زيد', 'المحيميد', 'جراحة عامة', 'General Surgery', 'Riyadh', 1),
('RHD016', 'مصطفى السيد', 'مصطفى', 'جراحة عامة / أورام', 'Oncology', 'Riyadh', 1),
('RHD017', 'خالد', 'أبو العلاء', 'جراحة عظام', 'Orthopedics', 'Riyadh', 1),
('RHD018', 'محمد', 'المثلوثي', 'جراحة عظام', 'Orthopedics', 'Riyadh', 1),
('RHD019', 'شريف', 'حافظ', 'جراحة مخ وأعصاب', 'Neurosurgery', 'Riyadh', 1),
('RHD020', 'صبري محمد', 'عبدالعظيم', 'جراحة أطفال', 'Pediatric Surgery', 'Riyadh', 1),
('RHD021', 'وليد خالد', 'السيد', 'جراحة وجه', 'Oral Surgery', 'Riyadh', 1),
('RHD022', 'يحيى اسماعيل', 'عقيل', 'جلدية', 'Dermatology', 'Riyadh', 1),
('RHD023', 'عمر محمد', 'دغريري', 'جهاز هضمي ومناظير', 'Gastroenterology', 'Riyadh', 1),
('RHD024', 'أمجد', 'سرور', 'جهاز هضمي', 'Gastroenterology', 'Riyadh', 1),
('RHD025', 'عبدالعزيز بن ناصر', 'الحقباني', 'جهاز هضمي', 'Gastroenterology', 'Riyadh', 1),
('RHD026', 'مجدي', 'الجمل', 'صدرية / عناية مركزة', 'Pulmonology', 'Riyadh', 1),
('RHD027', 'وليد نبيل', 'عثمان', 'طب الأسرة', 'Family Medicine', 'Riyadh', 1),
('RHD028', 'أحمد بن عباد', 'الحارثي', 'أسرة ومجتمع', 'Family Medicine', 'Riyadh', 1),
('RHD029', 'وليد عبدالرحمن', 'العوجان', 'طب الأسرة', 'Family Medicine', 'Riyadh', 1),
('RHD030', 'عبدالله', 'الشهراني', 'عيون', 'Ophthalmology', 'Riyadh', 1),
('RHD031', 'عوض سعد', 'القحطاني', 'عيون', 'Ophthalmology', 'Riyadh', 1),
('RHD032', 'خالد بن صالح', 'العنقري', 'عيون', 'Ophthalmology', 'Riyadh', 1),
('RHD033', 'سعد', 'الخليل', 'عيون / ماء أبيض', 'Ophthalmology', 'Riyadh', 1),
('RHD034', 'وليد', 'الخزيم', 'غدد صماء', 'Endocrinology', 'Riyadh', 1),
('RHD035', 'منصور محمد', 'القحطاني', 'قلب', 'Cardiology', 'Riyadh', 1),
('RHD036', 'محمد شريف', 'البلشي', 'كلى', 'Nephrology', 'Riyadh', 1),
('RHD037', 'جلال الدين', 'الشطوري', 'مخ وأعصاب', 'Neurology', 'Riyadh', 1),
('RHD038', 'يوسف', 'العريني', 'مخ وأعصاب', 'Neurology', 'Riyadh', 1),
('RHD039', 'وجدي', 'شداد', 'نساء وولادة', 'OB/GYN', 'Riyadh', 1),
('RHD040', 'وائل', 'عبدالباقي', 'نساء وولادة', 'OB/GYN', 'Riyadh', 1),
('RHD041', 'أيمن', 'جاد الرب', 'نساء وولادة', 'OB/GYN', 'Riyadh', 1),
('RHD042', 'منير', 'الشيخ', 'نساء وولادة', 'OB/GYN', 'Riyadh', 1),
('RHD043', 'فهد', 'الجاسر', 'مسالك بولية', 'Urology', 'Riyadh', 1),
('RHD044', 'أحمد', 'الزامل', 'مسالك بولية', 'Urology', 'Riyadh', 1),
('RHD045', 'راشد', 'القرني', 'نفسية', 'Psychiatry', 'Riyadh', 1),
('RHD046', 'حسن محمد', 'بخش', 'طب طبيعي وإعادة تأهيل', 'Rehabilitation', 'Riyadh', 1),
('RHD047', 'حسن', 'القحطاني', 'تخدير', 'Anesthesiology', 'Riyadh', 1);

-- Jazan (J001) - 15 doctors
INSERT OR IGNORE INTO providers (provider_code, first_name_ar, last_name_ar, specialty, department, clinic_location, is_active) VALUES
('JHD001', 'هشام حسين', 'كريري', 'باطنية / غدد صماء', 'Endocrinology', 'Jazan', 1),
('JHD002', 'أحمد عمر', 'مباركي', 'باطنية', 'Internal Medicine', 'Jazan', 1),
('JHD003', 'ريم يحيى', 'أبو هادي', 'أطفال', 'Pediatrics', 'Jazan', 1),
('JHD004', 'جمال', 'باحاج', 'أنف وأذن وحنجرة', 'ENT', 'Jazan', 1),
('JHD005', 'عاصم', 'العوامي', 'جراحة عظام', 'Orthopedics', 'Jazan', 1),
('JHD006', 'عمار', 'عبدالوارث', 'مسالك بولية', 'Urology', 'Jazan', 1),
('JHD007', 'زياد', 'النعيمي', 'جلدية', 'Dermatology', 'Jazan', 1),
('JHD008', 'محمد بدوي', 'سمره', 'جهاز هضمي ومناظير', 'Gastroenterology', 'Jazan', 1),
('JHD009', 'محمد', 'النعمي', 'عيون', 'Ophthalmology', 'Jazan', 1),
('JHD010', 'إلياس أحمد', 'باعوذه', 'عيون', 'Ophthalmology', 'Jazan', 1),
('JHD011', 'هاني إبراهيم', 'الحكمي', 'عيون', 'Ophthalmology', 'Jazan', 1),
('JHD012', 'وليد', 'الباشا', 'قلب / قسطرة قلبية', 'Cardiology', 'Jazan', 1),
('JHD013', 'حاتم طاهر', 'حامدي', 'مخ وأعصاب', 'Neurology', 'Jazan', 1),
('JHD014', 'محمد علي', 'حكمي', 'نساء وولادة', 'OB/GYN', 'Jazan', 1),
('JHD015', 'عبدالرحمن', 'الفيفي', 'نساء وولادة', 'OB/GYN', 'Jazan', 1),
('JHD016', 'أكرم عبدالله', 'سمرقندي', 'نساء وولادة', 'OB/GYN', 'Jazan', 1),
('JHD017', 'أنور علي', 'قاسم', 'نساء وولادة', 'OB/GYN', 'Jazan', 1),
('JHD018', 'أحمد', 'العمودي', 'باطنية / كبد', 'Gastroenterology', 'Jazan', 1),
('JHD019', 'مصطفى', 'شحاتة', 'تخدير', 'Anesthesiology', 'Jazan', 1);

-- Madinah (M001) - 15 doctors
INSERT OR IGNORE INTO providers (provider_code, first_name_ar, last_name_ar, specialty, department, clinic_location, is_active) VALUES
('MHD001', 'أحمد عبدالسلام', 'حسين', 'أطفال', 'Pediatrics', 'Madinah', 1),
('MHD002', 'عبدالمجيد', 'كردي', 'أطفال', 'Pediatrics', 'Madinah', 1),
('MHD003', 'محمد', 'عبدالهادي', 'أنف وأذن وحنجرة', 'ENT', 'Madinah', 1),
('MHD004', 'أحمد سيد', 'جاد', 'جراحة عظام', 'Orthopedics', 'Madinah', 1),
('MHD005', 'محمد', 'إبراهيم', 'جراحة مخ وأعصاب', 'Neurosurgery', 'Madinah', 1),
('MHD006', 'عثمان', 'عبدالرحمن', 'جراحة أطفال', 'Pediatric Surgery', 'Madinah', 1),
('MHD007', 'سامر', 'الخيري', 'جلدية', 'Dermatology', 'Madinah', 1),
('MHD008', 'ياسر', 'محروس', 'صدرية / جهاز تنفسي', 'Pulmonology', 'Madinah', 1),
('MHD009', 'يوسف', 'بخش', 'طب الأسرة', 'Family Medicine', 'Madinah', 1),
('MHD010', 'وليد', 'العطاس', 'عيون / ماء أبيض وشبكية', 'Ophthalmology', 'Madinah', 1),
('MHD011', 'عبدالله شفيق', 'الفحام', 'عيون / قرنية', 'Ophthalmology', 'Madinah', 1),
('MHD012', 'محمود', 'عبدالرحمن', 'غدد صماء', 'Endocrinology', 'Madinah', 1),
('MHD013', 'أشرف', 'جاد الرب', 'كلى', 'Nephrology', 'Madinah', 1),
('MHD014', 'أسامة', 'القرشي', 'مخ وأعصاب', 'Neurology', 'Madinah', 1),
('MHD015', 'محمد سعيد', 'العواجي', 'نساء وولادة', 'OB/GYN', 'Madinah', 1),
('MHD016', 'حافظ', 'شلقامي', 'نساء وولادة', 'OB/GYN', 'Madinah', 1),
('MHD017', 'سمير', 'درويش', 'نساء وولادة', 'OB/GYN', 'Madinah', 1),
('MHD018', 'مصطفى', 'عبدالقادر', 'مسالك بولية / أطفال', 'Pediatric Surgery', 'Madinah', 1),
('MHD019', 'بندر', 'القحطاني', 'طب طبيعي وإعادة تأهيل', 'Rehabilitation', 'Madinah', 1),
('MHD020', 'عبدالوهاب', 'عثمان', 'أشعة', 'Radiology', 'Madinah', 1);

-- Unayzah (U001) - 15 doctors
INSERT OR IGNORE INTO providers (provider_code, first_name_ar, last_name_ar, specialty, department, clinic_location, is_active) VALUES
('UHD001', 'أدهم', 'أسر', 'باطنية', 'Internal Medicine', 'Unayzah', 1),
('UHD002', 'عمر بن محمد', 'البياضي', 'أنف وأذن وحنجرة', 'ENT', 'Unayzah', 1),
('UHD003', 'محمد حامد', 'جوابرة', 'جراحة عامة', 'General Surgery', 'Unayzah', 1),
('UHD004', 'مصطفى', 'العيسوي', 'جراحة عظام', 'Orthopedics', 'Unayzah', 1),
('UHD005', 'هيثم', 'جادو', 'جراحة عظام', 'Orthopedics', 'Unayzah', 1),
('UHD006', 'عبدالله', 'سعيد', 'جهاز هضمي ومناظير', 'Gastroenterology', 'Unayzah', 1),
('UHD007', 'خالد محمد', 'الخلف', 'جهاز هضمي', 'Gastroenterology', 'Unayzah', 1),
('UHD008', 'أيمن', 'راشد', 'صدرية', 'Pulmonology', 'Unayzah', 1),
('UHD009', 'هشام محمد', 'قاضي', 'طب الأسرة', 'Family Medicine', 'Unayzah', 1),
('UHD010', 'خالد إبراهيم', 'الحميد', 'طب الأسرة', 'Family Medicine', 'Unayzah', 1),
('UHD011', 'إبراهيم عبدالرحمن', 'الهبدان', 'عيون / ماء أبيض', 'Ophthalmology', 'Unayzah', 1),
('UHD012', 'باسم', 'عطيوي', 'عيون', 'Ophthalmology', 'Unayzah', 1),
('UHD013', 'عمر محمد', 'سليمان', 'غدد صماء', 'Endocrinology', 'Unayzah', 1),
('UHD014', 'عبدالوهاب', 'جمال', 'قلب / قسطرة', 'Cardiology', 'Unayzah', 1),
('UHD015', 'طه محمد', 'جرادات', 'كلى', 'Nephrology', 'Unayzah', 1),
('UHD016', 'مازن', 'أبو حطب', 'مخ وأعصاب', 'Neurology', 'Unayzah', 1),
('UHD017', 'محمد رشيد', 'شريفي', 'مخ وأعصاب', 'Neurology', 'Unayzah', 1),
('UHD018', 'أسامة أحمد', 'حافظ', 'نساء وولادة', 'OB/GYN', 'Unayzah', 1),
('UHD019', 'أسامة محمد ابراهيم', 'حافظ', 'نساء وولادة', 'OB/GYN', 'Unayzah', 1),
('UHD020', 'عبدالعزيز', 'آل قويد', 'نساء وولادة', 'OB/GYN', 'Unayzah', 1),
('UHD021', 'عمر', 'السيد', 'نساء وولادة', 'OB/GYN', 'Unayzah', 1),
('UHD022', 'محمد ربيع', 'نفاع', 'مسالك بولية', 'Urology', 'Unayzah', 1),
('UHD023', 'عبدالسلام', 'جابر', 'تخدير', 'Anesthesiology', 'Unayzah', 1);
