name = "basma-crm"
main = "worker.js"
compatibility_date = "2026-04-30"
compatibility_flags = ["nodejs_compat"]

# Route
[[routes]]
pattern = "crm.brainsait.org/*"
zone_name = "brainsait.org"

[[d1_databases]]
binding = "DB"
database_name = "hnh-gharnata"
database_id = "d6960732-d5d0-4271-84e9-ba988c9c32dc"

[[services]]
binding = "HNH_SERVICE"
service = "hnh-unified"
